### ISSUE TITLE
cooler.create._ingest.BadInputError: Found bin ID < 0

### ISSUE THREAD

**Issue by xfcypeng** [wangyibin/CPhasing#2]
Traceback (most recent call last):
  File "/media/ps/4T/CPhasing/bin/cphasing", line 7, in <module>
    sys.exit(cli())
             ^^^^^
  File "/home/ps/anaconda3/envs/cphasing/lib/python3.12/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ps/anaconda3/envs/cphasing/lib/python3.12/site-packages/rich_click/rich_command.py", line 126, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/home/ps/anaconda3/envs/cphasing/lib/python3.12/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ps/anaconda3/envs/cphasing/lib/python3.12/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ps/anaconda3/envs/cphasing/lib/python3.12/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/media/ps/4T/CPhasing/cphasing/cli.py", line 995, in pipeline
    run(fasta, 
    ^^^^^^^^^^
  File "/media/ps/4T/CPhasing/cphasing/pipeline/pipeline.py", line 1090, in run
    plot.main(args=args,
  File "/home/ps/anaconda3/envs/cphasing/lib/python3.12/site-packages/rich_click/rich_command.py", line 126, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/home/ps/anaconda3/envs/cphasing/lib/python3.12/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ps/anaconda3/envs/cphasing/lib/python3.12/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/media/ps/4T/CPhasing/cphasing/cli.py", line 5052, in plot
    matrix = coarsen_matrix(matrix, factor, None, threads)   
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/media/ps/4T/CPhasing/cphasing/plot.py", line 648, in coarsen_matrix
    coarsen.main(args=[cool, 
    ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ps/anaconda3/envs/cphasing/lib/python3.12/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/home/ps/anaconda3/envs/cphasing/lib/python3.12/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ps/anaconda3/envs/cphasing/lib/python3.12/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ps/anaconda3/envs/cphasing/lib/python3.12/site-packages/cooler/cli/coarsen.py", line 84, in coarsen
    coarsen_cooler(
  File "/home/ps/anaconda3/envs/cphasing/lib/python3.12/site-packages/cooler/reduce.py", line 740, in coarsen_cooler
    create(
  File "/home/ps/anaconda3/envs/cphasing/lib/python3.12/site-packages/cooler/create/_create.py", line 681, in create
    nnz, ncontacts = write_pixels(
                     ^^^^^^^^^^^^^
  File "/home/ps/anaconda3/envs/cphasing/lib/python3.12/site-packages/cooler/create/_create.py", line 235, in write_pixels
    for i, chunk in enumerate(iterable):
  File "/home/ps/anaconda3/envs/cphasing/lib/python3.12/site-packages/cooler/create/_ingest.py", line 404, in _validate_pixels
    raise BadInputError("Found bin ID < 0")
cooler.create._ingest.BadInputError: Found bin ID < 0

**Comment by wangyibin** [comment]
Hi, 
Sorry for the late reply.
I failed to repeat this bug; I tried to fix this bug in the new version of  `v0.2.0.r278`. 

Best regards,
Yibin
